"""Agent 05 — PR Opener
Writes the patch + tests to disk and, if DRY_RUN=false, pushes a branch
and opens a real pull request. Defaults to dry-run so the graph never
touches a real repo by accident.
"""

import os
import subprocess
from datetime import datetime

from state import AgentState
from github_tools import open_pull_request


def pr_opener_agent(state: AgentState) -> AgentState:
    if state.get("error"):
        return state

    dry_run = os.getenv("DRY_RUN", "true").lower() != "false"
    out_dir = "output"
    os.makedirs(out_dir, exist_ok=True)

    patch_path = os.path.join(out_dir, "patch.diff")
    tests_path = os.path.join(out_dir, "tests.py")
    with open(patch_path, "w") as f:
        f.write(state.get("patch", ""))
    with open(tests_path, "w") as f:
        f.write(state.get("tests", ""))

    if dry_run:
        return {
            **state,
            "pr_url": None,
        }

    try:
        branch = f"agent-fix-issue-{state['issue_number']}-{datetime.now():%Y%m%d%H%M%S}"
        subprocess.run(["git", "checkout", "-b", branch], check=True)
        subprocess.run(["git", "apply", patch_path], check=True)
        subprocess.run(["git", "add", "-A"], check=True)
        subprocess.run(
            ["git", "commit", "-m", f"Fix #{state['issue_number']} (agent-generated)"],
            check=True,
        )
        subprocess.run(["git", "push", "-u", "origin", branch], check=True)

        pr_url = open_pull_request(
            repo=state["repo"],
            branch=branch,
            title=f"Fix #{state['issue_number']}: {state['issue'].splitlines()[0]}",
            body=f"Auto-generated by the multi-agent pipeline.\n\n**Plan:**\n{state['plan']}",
        )
        return {**state, "pr_url": pr_url}
    except Exception as e:
        return {**state, "error": f"pr_opener failed: {e}"}
